import type { NextPage } from "next";
import Head from "next/head";
import { Box, chakra } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <chakra.h1 color="tomato">Hello World</chakra.h1>
      </Box>
    </div>
  );
};

export default Home;
